name: Uçuş Verisi Gönder

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Her 30 dakikada bir

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Node.js kur
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Bağımlılıkları kur
        run: npm install

      - name: Veriyi çek ve gönder
        run: node sendData.js
