name: Esenboga Gelen Ucus

on:
  schedule:
    - cron: '0 */6 * * *' # Her 6 saatte bir çalışır
  workflow_dispatch: # Elle tetiklemek için

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run scraper and send data
      run: node sendData.js
